const { chromium } = require(process.env.CERNE_PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1180, height: 780 } });
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    await page.goto('http://127.0.0.1:14203/scripts/media-tests/harness.html');
    const composer = page.locator('.composer-input');
    await composer.waitFor();
    const image = page.getByTitle('Imagem direta: clique para ativar ou voltar ao chat de texto');
    const video = page.getByTitle('Vídeo direto: clique para ativar ou voltar ao chat de texto');
    await image.click();
    await composer.fill('PROMPT-IMAGEM-EXCLUSIVO');
    await page.locator('.send-btn').click();
    await page.locator('.media-card').first().waitFor();
    assert.equal(await image.getAttribute('aria-pressed'), 'true');
    const first = await page.evaluate(() => window.calls.filter(c => c.cmd === 'send_media_message')[0]);
    assert.equal(first.args.prompt, 'PROMPT-IMAGEM-EXCLUSIVO');
    assert.deepEqual(Object.keys(first.args).sort(), ['images', 'kind', 'prompt', 'sessionId']);
    assert.equal(await page.evaluate(() => window.calls.filter(c => c.cmd === 'send_message').length), 0);
    await page.locator('.image-preview').click();
    await page.locator('.full-image').waitFor();
    await page.getByRole('button', { name: 'Close' }).click();
    // Direct editor must accept images even when the text model has no vision.
    await composer.evaluate(el => {
      const canvas = document.createElement('canvas'); canvas.width = 512; canvas.height = 256;
      canvas.toBlob(blob => {
        const data = new DataTransfer(); data.items.add(new File([blob], 'edit.png', { type: 'image/png' }));
        el.dispatchEvent(new ClipboardEvent('paste', { clipboardData: data, bubbles: true, cancelable: true }));
      }, 'image/png');
    });
    await page.waitForFunction(() => document.querySelector('.attachment-chip') && !document.querySelector('.attachment-chip .spin'));
    await composer.fill('EDITAR-IMAGEM-ATUAL');
    await page.locator('.send-btn').click();
    await page.waitForFunction(() => window.calls.filter(c => c.cmd === 'send_media_message').length === 2);
    const edited = await page.evaluate(() => window.calls.filter(c => c.cmd === 'send_media_message')[1]);
    assert.equal(edited.args.images.length, 1);
    assert.equal(edited.args.prompt, 'EDITAR-IMAGEM-ATUAL');
    assert.equal(await page.evaluate(() => window.calls.filter(c => c.cmd === 'optimize_image_data_url').length), 0);
    await video.click();
    await composer.fill('PROMPT-VIDEO-EXCLUSIVO');
    await page.locator('.send-btn').click();
    // Cancelled directory picker must neither dispatch nor clear draft.
    assert.equal(await page.evaluate(() => window.calls.filter(c => c.cmd === 'send_media_message').length), 2);
    assert.equal(await composer.inputValue(), 'PROMPT-VIDEO-EXCLUSIVO');
    await page.evaluate(() => { window.dialogResult = 'C:/temporary-video-output'; });
    await page.evaluate(() => { window.failSave = true; });
    await page.locator('.send-btn').click();
    assert.equal(await page.evaluate(() => window.calls.filter(c => c.cmd === 'send_message').length), 0);
    assert.equal(await composer.inputValue(), 'PROMPT-VIDEO-EXCLUSIVO');
    await page.evaluate(() => { window.failSave = false; window.testProvider.config.video_gen.output_dir = ''; });
    await page.locator('.send-btn').click();
    const player = page.locator('video');
    await player.waitFor();
    await player.evaluate(v => new Promise((resolve, reject) => { if (v.readyState >= 1) resolve(); else { v.onloadedmetadata = resolve; v.onerror = reject; } }));
    assert.equal(await player.evaluate(v => v.duration), 1);
    await player.evaluate(v => v.play());
    assert.equal(await player.evaluate(v => v.paused), false);
    await video.click();
    await composer.fill('AGORA-TEXTO-NORMAL');
    await page.locator('.send-btn').click();
    const normal = await page.evaluate(() => window.calls.find(c => c.cmd === 'send_message'));
    assert.equal(normal.args.text, 'AGORA-TEXTO-NORMAL');
    const textHistory = await page.evaluate(() => window.testSession.messages.map(m => m.content));
    assert(!textHistory.includes('PROMPT-IMAGEM-EXCLUSIVO'));
    assert(!textHistory.includes('PROMPT-VIDEO-EXCLUSIVO'));
    await page.evaluate(async () => { window.testSession.status = 'idle'; await window.testSession.reloadCurrent(); });
    assert.equal(await page.locator('.media-card').count(), 3);
    await page.screenshot({ path: require('node:path').resolve(__dirname, '../../docs/direct-media-preview.png'), fullPage: true });
    await page.evaluate(() => { document.querySelector('#app').style.display = 'none'; window.mountVideoSettings(); });
    const settings = page.locator('.video-settings');
    await settings.getByLabel('Modelo', { exact: true }).fill('tested-video-model');
    await settings.getByLabel(/Formato da API/).selectOption('multipart');
    await settings.getByLabel('Chave da API de vídeo', { exact: true }).fill('fake-test-key');
    await settings.getByRole('button', { name: 'Salvar', exact: true }).click();
    await settings.getByText('Configuração salva', { exact: true }).waitFor();
    assert.equal(await page.evaluate(() => window.testProvider.config.video_gen.model), 'tested-video-model');
    assert.equal(await page.evaluate(() => window.videoKeySet), true);
    await settings.getByRole('button', { name: 'Remover chave', exact: true }).click();
    assert.equal(await page.evaluate(() => window.videoKeySet), false);
    await page.evaluate(() => window.mountImageSettings());
    const imageSettings = page.locator('#test-image-settings');
    await imageSettings.getByLabel(/API de imagem/).selectOption('openrouter');
    await imageSettings.getByText('A chave da conexão existente será reutilizada para imagem e vídeo.', { exact: true }).waitFor();
    await settings.getByLabel(/^API de vídeo/).selectOption('openrouter');
    await settings.getByText('A chave da conexão existente será reutilizada para imagem e vídeo.', { exact: true }).waitFor();
    assert.equal(await page.evaluate(() => window.testProvider.config.image_gen.connection_id), 'openrouter');
    assert.equal(await page.evaluate(() => window.testProvider.config.video_gen.connection_id), 'openrouter');
    assert.equal(await page.evaluate(() => window.calls.filter(c => c.cmd === 'set_media_provider_key' || c.cmd === 'set_openrouter_key').length), 0);
    await imageSettings.getByRole('button', { name: 'Carregar modelos' }).click();
    await imageSettings.getByLabel(/Modelos disponíveis/).selectOption('image-available-model');
    assert.equal(await page.evaluate(() => window.testProvider.config.image_gen.model), 'image-available-model');
    await settings.getByRole('button', { name: 'Carregar modelos' }).click();
    await settings.getByLabel(/Modelos disponíveis/).selectOption('video-available-model');
    assert.equal(await page.evaluate(() => window.testProvider.config.video_gen.model), 'video-available-model');
    // Recognized existing Google connection must be reused as well.
    await imageSettings.getByLabel(/API de imagem/).selectOption('gemini');
    assert.equal(await page.evaluate(() => window.testProvider.config.image_gen.connection_id), 'custom:existing-google');
    assert.equal(await imageSettings.getByLabel('Chave da API', { exact: true }).count(), 0);
    // A standalone vendor key is shared by image/video, and never copied into config JSON.
    await imageSettings.getByLabel(/API de imagem/).selectOption('xai');
    await imageSettings.getByLabel('Chave da API', { exact: true }).fill('test-only-vendor-key');
    await imageSettings.getByRole('button', { name: 'Salvar API', exact: true }).click();
    await page.waitForFunction(() => window.vendorKeySet?.xai === true);
    await settings.getByLabel(/^API de vídeo/).selectOption('xai');
    await settings.getByPlaceholder('Já configurada · compartilhada entre imagem e vídeo').waitFor();
    assert.equal(await page.evaluate(() => JSON.stringify(window.testProvider.config).includes('test-only-vendor-key')), false);
    assert.equal(await settings.getByLabel(/^API de vídeo/).locator('option[value="openai"]').count(), 0);
    await imageSettings.getByLabel(/API de imagem/).selectOption('openai');
    await imageSettings.getByLabel(/Modelo \/ endpoint/).fill('gpt-image-test');
    // Invalid extra JSON prevents a model request with stale persisted settings.
    await imageSettings.locator('summary').click();
    await imageSettings.locator('textarea').fill('[]');
    const prior = await page.evaluate(() => window.calls.filter(c => c.cmd === 'list_media_models').length);
    await imageSettings.getByRole('button', { name: 'Carregar modelos' }).click();
    await imageSettings.getByText(/Use um objeto JSON/).waitFor();
    assert.equal(await page.evaluate(() => window.calls.filter(c => c.cmd === 'list_media_models').length), prior);
    await imageSettings.locator('textarea').fill('{}');
    await imageSettings.getByRole('button', { name: 'Salvar API', exact: true }).click();
    await imageSettings.screenshot({ path: require('node:path').resolve(__dirname, '../../docs/media-api-selection-preview.png') });
    assert.deepEqual(errors, []);
    console.log('PASS: direct image, enlargement, folder cancellation, video playback, text/media isolation, persisted reload.');
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exit(1); });
